server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: inventory-service
    static_configs:
      - targets: [localhost]
        labels:
          job: inventory-service
          service: inventory-service
          __path__: /logs/inventory-service.log

  - job_name: order-fulfillment-service
    static_configs:
      - targets: [localhost]
        labels:
          job: order-fulfillment-service
          service: order-fulfillment-service
          __path__: /logs/order-fulfillment-service.log
